### ISSUE TITLE
yarn bootstrap fails

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4789]
#### Description
`yarn bootstrap` fails to complete

#### Repro Steps
`yarn bootstrap`

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.2
 - OS: Mac OS X 10.15.5

#### Logs

```
yarn run v1.12.1
$ PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn && ocular-bootstrap
[1/4] 🔍  Resolving packages...
success Already up-to-date.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "puppeteer > ws@7.3.1" has unmet peer dependency "bufferutil@^4.0.1".
warning "puppeteer > ws@7.3.1" has unmet peer dependency "utf-8-validate@^5.0.2".
[4/4] 📃  Building fresh packages...
warning "puppeteer@5.1.0" has no binaries
[1/4] 🔍  Resolving packages...
success Already up-to-date.
npm WARN lifecycle The node binary used for scripts is /var/folders/pp/yv64x66n3_v45sgbw1f7qkj80000gn/T/yarn--1594857908411-0.38158089748014357/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> deck.gl-monorepo@ build /Users/steve/Code/deck.gl
> ocular-clean && ocular-build && lerna run build

Building modules/test-utils
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/steve/Code/deck.gl/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/steve/Code/deck.gl/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deck.gl-monorepo@ build: `ocular-clean && ocular-build && lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deck.gl-monorepo@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steve/.npm/_logs/2020-07-16T00_05_11_252Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Pessimistress** [comment]
Looks like it's Node version related: https://github.com/babel/babel/issues/11216

We need to upgrade the babel dependencies on yarn.lock.

**Comment by kylebarron** [comment]
What Node version are you using? I have my Node set to `v12.16.3` since I believe `v12.17` gave me a similar error, or maybe that was on Loaders.gl.

**Comment by stevenroussey-privicy** [comment]
node -v
v12.18.0

**Comment by kylebarron** [comment]
Yeah I'd suggest using NVM to use 12.16.3, and that will probably work without any deck.gl changes

**Comment by stevenroussey-privicy** [comment]
OK, will do. Might add a node version check for supported versions.

Steven Roussey
Privicy Inc. <https://www.privicy.com/>

ᐧ

**Comment by Pessimistress** [comment]
@stevenroussey-privicy Can you pull master and try again?

**Comment by stevenroussey-privicy** [comment]
Success!
