### ISSUE TITLE
Unit test failing with 'TypeError: onBeforeUpdate is not a function'

### ISSUE THREAD

**Issue by srideviayyagari** [visgl/deck.gl#5219]
Hi,

I'm trying to run a simple unit test and it is failing with "TypeError: onBeforeUpdate is not a function". 
Can you please let me know if there is some issue with my code that is causing this issue. I have tried with a blank data too to check if thee is some issue with my data itself. But, getting the same issue.
Thank you,

App.test.js
-----------
import test from 'tape-catch';
import {testLayer, generateLayerTests} from '@deck.gl/test-utils';
import {GeoJsonLayer} from '@deck.gl/layers';

test('GeoJsonLayer#tests', t => {
  
  const testCases = generateLayerTests({
    Layer: GeoJsonLayer,
    sampleProps: {
      data: [{
        "id": "track1",
        "type": "track",
        "path": [
          [0, 0],
          [60, 0]
        ],
        "status": "vacant",
        "direction": "S",
        "show": 1
      }]
    },
    assert: ({layer, subLayers}) => {
      //t.ok(layer.state.features, 'should update features');
      //t.is(subLayers.length, layer.props.stroked ? 2 : 1, 'correct number of sublayers');
      t.is(1, 1, "GOOODDD!!!!!!!!!!!!!");
    }
  });

  testLayer({Layer: GeoJsonLayer, testCases});

  t.end();
});

After running 'npm test', this is the error I'm getting.

 RUNS  src/App.test.js
TAP version 13
# GeoJsonLayer#tests     
ok 1 GOOODDD!!!!!!!!!!!!!
not ok 2 TypeError: onBeforeUpdate is not a function
  ---
    operator: error
    at: Test.Object.<anonymous>.exports.Test.run (C:\Sri\unittest\node_modules\tape-catch\index.js:29:10)      
    stack: |-
      TypeError: onBeforeUpdate is not a function
          at onBeforeUpdate (C:\Sri\unittest\node_modules\@deck.gl\test-utils\src\generate-layer-tests.js:90:7)
          at runLayerTestUpdate (C:\Sri\unittest\node_modules\@deck.gl\test-utils\src\lifecycle-test.js:188:5) 
          at _loop (C:\Sri\unittest\node_modules\@deck.gl\test-utils\src\lifecycle-test.js:61:39)
          at testLayer (C:\Sri\unittest\node_modules\@deck.gl\test-utils\src\lifecycle-test.js:57:37)
          at Test.<anonymous> (C:\Sri\unittest\src\App.test.js:33:28)
          at Test.bound [as _cb] (C:\Sri\unittest\node_modules\tape\lib\test.js:84:32)
          at Test.Object.<anonymous>.exports.Test.run (C:\Sri\unittest\node_modules\tape-catch\index.js:26:10)
          at Test.bound [as run] (C:\Sri\unittest\node_modules\tape\lib\test.js:84:32)
          at Immediate.next [as _onImmediate] (C:\Sri\unittest\node_modules\tape\lib\results.js:85:19)
 FAIL  src/App.test.jsmediate (internal/timers.js:461:21)
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
      at node_modules/@jest/core/build/TestScheduler.js:304:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.Typed.emit (node_modules/emittery/index.js:258:23)

  console.log
    deck: deck.gl 8.3.6 - set deck.log.level=1 (or higher) to trace attribute updates

      at Object.<anonymous> (node_modules/@deck.gl/core/src/lib/init.js:45:5)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        9.779 s
Ran all test suites related to changed files.

**Comment by Pessimistress** [comment]
Does it work if you add this?

```js
generateLayerTests({..., onBeforeUpdate: () => {}});
```

**Comment by srideviayyagari** [comment]
Hi, Thank you for your reply.

tried to include it in my code. 'generateLayerTests({..., onBeforeUpdate: () => {}});'
But, getting Jest error for unexpected token. 
  
  const testCases = generateLayerTests({
    Layer: GeoJsonLayer,
    sampleProps: {
      data: [{
        "id": "track1",
        "type": "track",
        "path": [
          [0, 0],
          [60, 0]
        ],
        "status": "vacant",
        "direction": "S",
        "show": 1
      }]
    },
    assert: ({layer, subLayers}) => {
      //t.ok(layer.state.features, 'should update features');
      //t.is(subLayers.length, layer.props.stroked ? 2 : 1, 'correct number of sublayers');
    
      t.is(1, 1, "GOOODDD!!!!!!!!!!!!!");
    }
  });
  generateLayerTests({..., onBeforeUpdate: () => {}});
  testLayer({Layer: GeoJsonLayer, testCases});

  t.end();
});


-------------
 FAIL  src/App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: C:\Sri\unittest\src\App.test.js: Unexpected token (29:25)

      27 |     }
      28 |   });
    > 29 |   generateLayerTests({..., onBeforeUpdate: () => {}});
         |                          ^
      30 |   testLayer({Layer: GeoJsonLayer, testCases});
      31 | 
      32 |   t.end();

      at _temp._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at _temp.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at _temp.raise (node_modules/@babel/parser/src/parser/error.js:39:17)
      at _temp.unexpected (node_modules/@babel/parser/src/parser/util.js:139:16)
      at _temp.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1171:20)
      at _temp.parseExprAtom (node_modules/@babel/parser/src/plugins/jsx/index.js:535:22)
      at _temp.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:568:23)
      at _temp.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:548:21)
      at _temp.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:532:17)
      at _temp.parseExprOps (node_modules/@babel/parser/src/parser/expression.js:348:23)

Test Suites: 1 failed, 1 total

**Comment by Pessimistress** [comment]
That's not valid JavaScript. I meant adding `onBeforeUpdate: () => {}` to your `generateLayerTests` call.
