### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#5230]
I followed the  instruction on this page: https://deck.gl/docs/contributing. I tried to set up the dev environment on Ubuntu 20.04 LTS using WSL2. 

```
git checkout master
yarn bootstrap
yarn test
```
And I got this error when executing "yarn test":
```
dev@DESKTOP-483TONB:~/deck.gl/test$ yarn test
yarn run v1.22.5
$ ocular-test
test [ 'full' | 'fast' | 'dist' | 'bench' | 'ci' | 'cover' ]
Running 'full' test by default
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1607315068398-0.5102556319899185/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> deck.gl-monorepo@ lint /home/dev/deck.gl
> ocular-lint

Checking prettier code style in {modules,examples,test}...
All files using prettier code style.
Running eslint in {modules,examples,test}...
Lockfile valid.
Running node tests...
deck: deck.gl untranspiled source - set deck.log.level=1 (or higher) to trace attribute updates
/home/dev/deck.gl/test/node.js:37
**canvas.width = gl.drawingBufferWidth;**
                  ^

TypeError: Cannot read property 'drawingBufferWidth' of null
    at Object.<anonymous> (/home/dev/deck.gl/test/node.js:37:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/dev/deck.gl/node_modules/ocular-dev-tools/node/test.js:45:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dev@DESKTOP-483TONB:~/deck.gl/test$
```
Is the test suite broken in the master branch?

Thanks,

**Comment by Pessimistress** [comment]
Please follow the section "develop on windows" in the same document.

**Comment by txtl** [comment]
I updated to WSL2, which the section is not applicable. 

Updated: 

I tried with Ubuntu in a VM. I was able to execute the tests with 1 test failed:
```
1..1640
# tests 1640
# pass 1639
# fail 1
```

It seems to be something wrong with the WSL2 setup. 

Thanks,

**Comment by TextTL** [comment]
I've just ran the browser test. I have this result:

```
1..4725
# tests 4725
# pass  4679
# fail  46

```
sample log:
[deck.gl-test-browser.docx](https://github.com/visgl/deck.gl/files/5651197/deck.gl-test-browser.docx)
```

```

**Comment by txtl** [comment]
I've just run browser test, and I got this result:
[deck.gl-test-browser.docx](https://github.com/visgl/deck.gl/files/5651210/deck.gl-test-browser.docx)

**Comment by txtl** [comment]
for WSL2, I followed this post: https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2 , and disabled the firewall. It works now.


Thank you very much!
