### ISSUE TITLE
Error using a frozen array for `layer.coordinateOrigin`

### ISSUE THREAD

**Issue by rachel-skydio** [visgl/deck.gl#6480]
#### Description
Passing a frozen array to `layer.coordinateOrigin` produces an error like this:

```
TypeError: drawing LineLayer({id: 'line'}) to screen: Cannot assign to read only property '2' of object '[object Array]'
```

This happens unsurprisingly on both layer types that I tested, `PolygonLayer` and `LineLayer`.

This is especially annoying when the data passed to deck.gl is coming from a store where everything is immutable by default (e.g., when using immer or graphql w/ readonly fields).

Side note: a similar error happens when passing a frozen (parsed gltf) object to `ScenegraphLayer.scenegraph`.

#### Expected Behavior
I should be able to give frozen objects to deck.gl. Deck.gl should not mutate my data.

#### Repro Steps
[Codepen repro](https://codepen.io/rachel-skydio/pen/bGoEJoj)
[Codesandbox repro](https://codesandbox.io/s/frozen-layer-coordinateorigin-error-w85q4?file=/index.html) (prints error to console correctly)

Pass the following `coordinateOrigin` to a layer: 
```
const coordinateOrigin = [0, 0, 0];
Object.freeze(coordinateOrigin);
```

#### Environment
Reproduced with current deck.gl examples.

Tested browsers:

- Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- Firefox 88.0 (64-bit)

#### Logs

Error from [Codesandbox repro](https://codesandbox.io/s/frozen-layer-coordinateorigin-error-w85q4?file=/index.html):

```
TypeError: drawing LineLayer({id: 'line'}) to screen: Cannot assign to read only property '2' of object '[object Array]'
    at d (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:363721)
    at https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:361482
    at https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:361811
    at https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:232819
    at p (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:364127)
    at t.getUniforms [as getModuleUniforms] (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:277141)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:277942)
    at https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:271999
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:217806)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:217873)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:64289)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:62616)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:261351)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:259619)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:1:259080)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:157542)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:374939)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:369353)
    at n.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:375674)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:342705)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:344446)
    at t.value (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:341180)
    at e (https://unpkg.com/deck.gl@%5E8.0.0/dist.min.js:11:343293)
```

**Comment by Pessimistress** [comment]
Thanks for reporting this. Fixed in v8.6.5.
