### ISSUE TITLE
[Bug] Deck.gl Build Problems in CRA/Vite

### ISSUE THREAD

**Issue by arthurgailes** [visgl/deck.gl#6906]
### Description

Hello,

I'm experiencing a problem as of 8.7.9 that seems to trace back to an updated loaders.gl dependency, but I'm not sure. I've created several maps from CRA and Vite, so I don't think this is intrinsic to the platforms, but each is returning a slightly different error.

The CRA error:

Vite:

To reproduce, 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

I run either `npx create-react-app myapp` or npm `create vite my-app`, install deck.gl, and then load the basic example.

The js code is ripped from the example:
```

import React from "react";
import { render } from "react-dom";
import DeckGL, { GeoJsonLayer, ArcLayer } from "deck.gl";

// source: Natural Earth http://www.naturalearthdata.com/ via geojson.xyz
const COUNTRIES =
  "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_admin_0_scale_rank.geojson"; //eslint-disable-line
const AIR_PORTS =
  "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_airports.geojson";

const INITIAL_VIEW_STATE = {
  latitude: 51.47,
  longitude: 0.45,
  zoom: 4,
  bearing: 0,
  pitch: 30,
};

function App() {
  const onClick = (info) => {
    if (info.object) {
      // eslint-disable-next-line
      alert(
        `${info.object.properties.name} (${info.object.properties.abbrev})`
      );
    }
  };

  return (
    <DeckGL controller={true} initialViewState={INITIAL_VIEW_STATE}>
      <GeoJsonLayer
        id="base-map"
        data={COUNTRIES}
        stroked={true}
        filled={true}
        lineWidthMinPixels={2}
        opacity={0.4}
        getLineColor={[60, 60, 60]}
        getFillColor={[200, 200, 200]}
      />
      <GeoJsonLayer
        id="airports"
        data={AIR_PORTS}
        filled={true}
        pointRadiusMinPixels={2}
        pointRadiusScale={2000}
        getPointRadius={(f) => 11 - f.properties.scalerank}
        getFillColor={[200, 0, 80, 180]}
        pickable={true}
        autoHighlight={true}
        onClick={onClick}
      />
      <ArcLayer
        id="arcs"
        data={AIR_PORTS}
        dataTransform={(d) =>
          d.features.filter((f) => f.properties.scalerank < 4)
        }
        getSourcePosition={(f) => [-0.4531566, 51.4709959]}
        getTargetPosition={(f) => f.geometry.coordinates}
        getSourceColor={[0, 128, 200]}
        getTargetColor={[200, 0, 80]}
        getWidth={1}
      />
    </DeckGL>
  );
}

export default App;

```

### Environment

- Framework version: 8.7.9
- Browser: N/A
- OS: Linux/Windows

### Logs

**Vite:**

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/@loaders.gl/loader-utils/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/@deck.gl/core/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/deck.gl/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/@loaders.gl/textures/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/@loaders.gl/draco/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

✘ [ERROR] No matching export in "browser-external:worker_threads" for import "Worker"

    node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9:
      2 │ import { Worker as NodeWorker } from 'worker_threads';
        ╵          ~~~~~~

12:59:02 PM [vite] error while updating dependencies:
Error: Build failed with 6 errors:
node_modules/@deck.gl/core/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9: ERROR: No matching export in "browser-external:worker_threads" for import "Worker"
node_modules/@loaders.gl/draco/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9: ERROR: No matching export in "browser-external:worker_threads" for import "Worker"
node_modules/@loaders.gl/loader-utils/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9: ERROR: No matching export in "browser-external:worker_threads" for import "Worker"
node_modules/@loaders.gl/textures/node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9: ERROR: No matching export in "browser-external:worker_threads" for import "Worker"
node_modules/@loaders.gl/worker-utils/dist/esm/lib/worker-farm/worker-thread.js:2:9: ERROR: No matching export in "browser-external:worker_threads" for import "Worker"
...
    at failureErrorWithLog (/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:1603:15)
    at /home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:1249:28
    at runOnEndCallbacks (/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:1247:7)
    at /home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:1356:14
    at /home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl-test/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)

**CRA:**

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 18:25-38
export 'FixedSizeList' (imported as 'FixedSizeList') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 18:49-54
export 'Field' (imported as 'Field') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 19:22-27
export 'Field' (imported as 'Field') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 20:21-25
export 'Data' (imported as 'Data') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 21:27-46
export 'FixedSizeListVector' (imported as 'FixedSizeListVector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 26:21-27
export 'Schema' (imported as 'Schema') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 27:26-37
export 'RecordBatch' (imported as 'RecordBatch') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 28:20-25
export 'Table' (imported as 'Table') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 5:17-21
export 'Int8' (imported as 'Int8') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 8:17-22
export 'Uint8' (imported as 'Uint8') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 11:17-22
export 'Int16' (imported as 'Int16') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 14:17-23
export 'Uint16' (imported as 'Uint16') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 17:17-22
export 'Int32' (imported as 'Int32') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 20:17-23
export 'Uint32' (imported as 'Uint32') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 23:17-24
export 'Float32' (imported as 'Float32') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 26:17-24
export 'Float64' (imported as 'Float64') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 35:13-28
export 'Int8Vector' (imported as 'Int8Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 38:13-29
export 'Uint8Vector' (imported as 'Uint8Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 41:13-29
export 'Int16Vector' (imported as 'Int16Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 44:13-30
export 'Uint16Vector' (imported as 'Uint16Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 47:13-29
export 'Int32Vector' (imported as 'Int32Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 50:13-30
export 'Uint32Vector' (imported as 'Uint32Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 53:13-31
export 'Float32Vector' (imported as 'Float32Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/lib/arrow/arrow-type-utils.js 56:13-31
export 'Float64Vector' (imported as 'Float64Vector') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 17:0-43
Module not found: Error: Can't resolve './io/adapters' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'adapters.mjs'?
BREAKING CHANGE: The request './io/adapters' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 18:0-42
Module not found: Error: Can't resolve './builder/index' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'index.mjs'?
BREAKING CHANGE: The request './builder/index' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 19:0-97
Module not found: Error: Can't resolve './ipc/reader' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'reader.mjs'?
BREAKING CHANGE: The request './ipc/reader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 20:0-97
Module not found: Error: Can't resolve './ipc/writer' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'writer.mjs'?
BREAKING CHANGE: The request './ipc/writer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 21:0-51
Module not found: Error: Can't resolve './io/whatwg/iterable' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'iterable.mjs'?
BREAKING CHANGE: The request './io/whatwg/iterable' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 22:0-62
Module not found: Error: Can't resolve './io/whatwg/builder' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'builder.mjs'?
BREAKING CHANGE: The request './io/whatwg/builder' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/apache-arrow/Arrow.dom.mjs 23:0-71
Module not found: Error: Can't resolve './io/whatwg/reader' in '/home/ExtraFiles/GoogleDrive/AEI/sites/deckgl_cra_test/node_modules/apache-arrow'
Did you mean 'reader.mjs'?
BREAKING CHANGE: The request './io/whatwg/reader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by Pessimistress** [comment]
This is caused by loaders.gl release 3.2.0. Created issues in loaders.gl. A temporary work around is to add the following to your package.json:

```json
"resolutions": {
  "@loaders.gl/core": "3.1.8",
  "@loaders.gl/images": "3.1.8"
}
```

**Comment by arthurgailes** [comment]
Thank you for the quick response. This did not change the issue in either build. After adding to the package.json, I also deleted node_modules/package-lock.json and ran `npm cache clean --force` to no avail.

My package.json in CRA:
```

{
  "name": "deckgl_cra_test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^13.5.0",
    "deck.gl": "^8.7.9",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "resolutions": {
    "@loaders.gl/core": "3.1.8",
    "@loaders.gl/images": "3.1.8"
  }
}

```

**Comment by Pessimistress** [comment]
`resolutions` works for yarn only. For npm you need [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).

**Comment by arthurgailes** [comment]
Thanks. The following worked for me:

```
  "overrides": {
    "@loaders.gl/core": "3.1.8",
    "@loaders.gl/images": "3.1.8",
    "@loaders.gl/3d-tiles": "3.1.8",
    "@loaders.gl/gis": "3.1.8",
    "@loaders.gl/textures": "3.1.8",
    "@loaders.gl/terrain": "3.1.8",
    "@loaders.gl/schema": "3.1.8",
    "@loaders.gl/gltf": "3.1.8",
    "@loaders.gl/tiles": "3.1.8",
    "@loaders.gl/loader-utils": "3.1.8"
  }
```

A note for others: the bottom three (gltf, tiles, loader-utils) were needed for Vite, but not CRA/Webpack. YMMV. The following helps for tracing down the offending packages: `npm why @loaders.gl/tiles@3.2.0`. You'll have to delete your node_modules and package-lock.json files if using npm.

**Comment by Pessimistress** [comment]
loaders.gl 3.2.1 fixed build for vite. Still working on webpack 5 (cra) compatibility.

**Comment by Pessimistress** [comment]
loaders.gl 3.2.2 fixed build for webpack 5/CRA.

**Comment by arthurgailes** [comment]
One outstanding issue: the vite problem still requires "overrides", though it works with 3.2.2. The problem appears to be that @loaders.gl/worker-utils is imported specifically at 3.2.0:

```
deckgl-test > deck.gl > @deck.gl/aggregation-layers > @deck.gl/core > @loaders.gl/core > @loaders.gl/loader-utils > @loaders.gl/worker-utils@3.2.0
```

**Comment by belom88** [comment]
Try to clean-up you `yarn.lock` or `package-lock.json` from `@loaders.gl/....@^3.2.0...`

**Comment by sadrda** [comment]
I got it working with @arthurgailes answer. Note that you need at least npm v8.3 to use overrides.
