### ISSUE TITLE
[Bug] Layer render Error "TypeError: Cannot assign to read only property 'context' of object '[object Object]'` 

### ISSUE THREAD

**Issue by Awen-hub** [visgl/deck.gl#7196]
### Description

I have encountered an error `TypeError: Cannot assign to read only property 'context' of object '[object Object]'` when rendering a layer.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Here is my [demo](https://codesandbox.io/s/goofy-merkle-glt0cg?file=/src/App.js) in codesandbox.

### Environment

- Framework version: deck.gl@8.8.7
- Browser: Chrome 100
- OS: Ubuntu 20

### Logs

TypeError
Cannot assign to read only property 'context' of object '[object Object]'
    at LayerManager.setLayers (https://glt0cg.csb.app/node_modules/deck.gl/core/dist/esm/lib/layer-manager.js:115:21
    at LayerManager.updateLayers (https://glt0cg.csb.app/node_modules/deck.gl/core/dist/esm/lib/layer-manager.js:123:12
    at Deck._onRenderFrame (https://glt0cg.csb.app/node_modules/deck.gl/core/dist/esm/lib/deck.js:581:23
    at AnimationLoop.onRender (https://glt0cg.csb.app/node_modules/luma.gl/engine/dist/esm/lib/animation-loop.js:171:23
    at AnimationLoop._renderFrame (https://glt0cg.csb.app/node_modules/luma.gl/engine/dist/esm/lib/animation-loop.js:240:10
    at AnimationLoop.redraw (https://glt0cg.csb.app/node_modules/luma.gl/engine/dist/esm/lib/animation-loop.js:116:10
    at renderFrame (https://glt0cg.csb.app/node_modules/luma.gl/engine/dist/esm/lib/animation-loop.js:190:12

**Comment by Pessimistress** [comment]
This is not a deck.gl bug. Recoil freezes the objects you pass through it. You should consult their documentation for a solution.
