### ISSUE TITLE
[Bug] Accessors added by extensions not diffed correctly

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#7496]
### Description

When the `_propTypes` object [is created](https://github.com/visgl/deck.gl/blob/c1d3921798720280a9a4c99e298bdadc0d1d6ef8/modules/core/src/lifecycle/create-props.ts#L97) for a Layer the props added by any extensions are not considered. 

Later in the render cycle [when layers are diffed](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lifecycle/props.ts#L144-L164), any accessors that are added by an extension are considered to be changing shallowly as the propType for the extension accessor is not present on `Layer._propTypes`.

The impact is that state updates happen needlessly on every frame.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

An accessor added by an extension behaves the same as a standard accessor, in that it invokes the [default accessor equality function](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lifecycle/prop-types.ts#L131-L136).

### Steps to Reproduce

Add the following test to `test/modules/core/lib/layer-extension.spec.js`:

```javascript
// Modify MockExtension.updateState to include:
MockExtension.changeFlags = updateParams.changeFlags;

test('LayerExtension#props diff', t => {
  const extension = new MockExtension({assert: t.ok});

  MockExtension.resetStats();

  testLayer({
    Layer: ScatterplotLayer,
    testCases: [
      {
        props: {
          id: 'test-layer',
          data: [
            {coordinates: [-122, 38], value: 1},
            {coordinates: [-123, 37], value: 2}
          ],
          getPosition: d => d.coordinates,
          ext_getValue: d => d.value,
          extensions: [extension]
        },
        onAfterUpdate: ({layer}) => {
          t.is(MockExtension.initializeCalled, 1, 'initializeState called');
          t.is(MockExtension.updateCalled, 1, 'updateState called');
          t.is(MockExtension.finalizeCalled, 0, 'finalizeState not called');
        }
      },
      {
        updateProps: {
          getPosition: d => [12, 34]
        },
        onAfterUpdate: () => {
          t.is(MockExtension.updateCalled, 1, 'updateState not called');
          t.is(
            MockExtension.changeFlags.propsChanged,
            'init',
            'props changeFlags unchanged from init'
          );
        }
      },
      {
        updateProps: {
          ext_getValue: d => 3
        },
        onAfterUpdate: () => {
          t.is(MockExtension.updateCalled, 1, 'updateState not called');
          t.is(
            MockExtension.changeFlags.propsChanged,
            'init',
            'props changeFlags unchanged from init'
          );
        }
      }
    ],
    onError: t.notOk
  });

  t.is(MockExtension.finalizeCalled, 1, 'finalizeState called');

  t.end();
});
```

### Environment

- Framework version: deck.gl@8.8.20
- Browser: all
- OS: all

### Logs

Test results

```bash
# LayerExtension#props diff
ok 1 initializeState: Self is layer instance
ok 2 initializeState: context received
ok 3 updateState: Self is layer instance
ok 4 updateState: changeFlags received
ok 5 initializeState called
ok 6 updateState called
ok 7 finalizeState not called
ok 8 updateState not called
ok 9 props changeFlags unchanged from init
ok 10 updateState: Self is layer instance
ok 11 updateState: changeFlags received
not ok 12 updateState not called
  ---
    operator: equal
    expected: 1
    actual:   2
    at: Object.onAfterUpdate (/Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:227:13)
    stack: |-
      Error: updateState not called
          at Test.assert [as _assert] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:385:10)
          at Test.is (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
          at Object.onAfterUpdate (/Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:227:13)
          at runLayerTestPostUpdateCheck (/Users/carto/git/visgl/deck.gl/modules/test-utils/src/lifecycle-test.js:187:14)
          at testLayer (/Users/carto/git/visgl/deck.gl/modules/test-utils/src/lifecycle-test.js:77:5)
          at /Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:189:3
          at Test.<anonymous> (/Users/carto/git/visgl/deck.gl/node_modules/tape-promise/index.compiled.js:86:19)
          at Test.bound [as _cb] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
  ...
not ok 13 props changeFlags unchanged from init
  ---
    operator: equal
    expected: 'init'
    actual:   'props.ext_getValue changed shallowly'
    at: Object.onAfterUpdate (/Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:228:13)
    stack: |-
      Error: props changeFlags unchanged from init
          at Test.assert [as _assert] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:385:10)
          at Test.is (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
          at Object.onAfterUpdate (/Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:228:13)
          at runLayerTestPostUpdateCheck (/Users/carto/git/visgl/deck.gl/modules/test-utils/src/lifecycle-test.js:187:14)
          at testLayer (/Users/carto/git/visgl/deck.gl/modules/test-utils/src/lifecycle-test.js:77:5)
          at /Users/carto/git/visgl/deck.gl/test/modules/core/lib/layer-extension.spec.js:189:3
          at Test.<anonymous> (/Users/carto/git/visgl/deck.gl/node_modules/tape-promise/index.compiled.js:86:19)
          at Test.bound [as _cb] (/Users/carto/git/visgl/deck.gl/node_modules/tape/lib/test.js:77:32)
  ...
ok 14 finalizeState: Self is layer instance
ok 15 finalizeState called

1..15
# tests 15
# pass  13
# fail  2

```

**Comment by Pessimistress** [comment]
This is a known limitation of the extensions system. We should not modify a static field of a class (`Layer._propTypes`) based on the prop value of one instance.

Back when extensions were proposed, we considered the HOC pattern:

```js
const DataFilterScatterplotLayer = withExtensions(ScatterplotLayer, new DataFilterExtension())

// Basically a sub class of ScatterplotLayer with additional prop types
new DataFilterScatterplotLayer({
  ...  
});
```

We did not pick this design because it was perceived as less convenient to use.

@ibgreen

**Comment by felixpalmer** [comment]
This does have a real impact, for example the `TileLayer` recrates all sublayers when any prop changes. It gives the impression that extensions are less performant than they are in reality. Two options I see in how we could fix it:

- Modify [`getPropTypes()`](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lifecycle/props.ts#L261-L265) so that it appends the prop types of any extensions present
- Add all the accessor prop types that extensions could add to the base `Layer` class
