### ISSUE TITLE
[Bug] TypeError: Cannot add property padding, object is not extensible

### ISSUE THREAD

**Issue by danielhuntleymclaren** [visgl/deck.gl#7619]
### Description

When adding a deck.gl map from the DOM it can sometimes raise the following error
```
position-children-under-views.ts:60 Uncaught TypeError: Cannot add property padding, 
object is not extensible at positionChildrenUnderViews (position-children-under-views.ts:60:17)
```

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

*Will try and pull together a complete sandbox but here is a snippet of code demonstrating where the error is triggering from.

```
import DeckGL from "@deck.gl/react/typed";
import { Map } from "react-map-gl";
import { useState } from "react";

const [maps, setMaps] = useState(input);
const viewState = {longitude:...};

const handleClick = () => {
    setMaps([...maps, newMap])
}

maps.map((item) => (
    <DeckGL
        viewState={viewState}
        ...
     >
    <Map .../>
    </DeckGL>
)); 
```

### Environment

Framework version: deck.gl@8.8.22
Browser: Chrome Version 109.0.5414.120
OS: Windows 10

### Logs

```
Uncaught TypeError: Cannot add property padding, object is not extensible
    at positionChildrenUnderViews (position-children-under-views.ts:60:17)
    at deckgl.ts:254:32
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26560:12)
```

**Comment by danielhuntleymclaren** [comment]
Resolve the issue above by passing in 
```
viewState={{...viewState}}
```

**Comment by Pessimistress** [comment]
If you are setting `viewState` to a viewport instance, don't do it. See https://github.com/visgl/deck.gl/discussions/7526
