### ISSUE TITLE
[Bug] Map freezes when offscreen

### ISSUE THREAD

**Issue by dcooley** [visgl/deck.gl#8226]
### Description

- Webpage with a navbar and two tabs
- Map loads correctly and displays in first tab
- Select second tab, then back to first
- The map has frozen with the error `Cannot read properties of undefined (reading 'width')`.

The error occurs from https://unpkg.com/deck.gl@8.9.12/dist.min.js onwards, specifically it's [this commit](https://github.com/visgl/deck.gl/commit/7f2dd447b51cb4e6c35b2e8ac28dab80e9cb95a6) that introduced this bug.

(and found and reported here - https://github.com/SymbolixAU/mapdeck/issues/373)

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The map does not freeze when offscreen

### Steps to Reproduce

An exmaple showing this behaviour is at this jsfiddle - https://jsfiddle.net/symbolixau/hmdjx3f9/82/ 

full code (mapbox token omitted):

```html
<html>
  <head>
     <script src="https://unpkg.com/deck.gl@8.9.12/dist.min.js"></script>
    <!-- only if base map is needed -->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet' />

<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:10; bottom:0; width:100%; height: 90% }

  .navbar {
    background-color: #333;
    overflow: hidden;
  }

  .navbar a {
    float: left;
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    }

    .navbar a:hover {
      background-color: #ddd;
      color: black;
    }

    /* Style for the tabs */
    .tab {
      display: none;
    }
  </style>
</head>


<body>
  
<div class="navbar">
    <a href="javascript:void(0)" onclick="openTab('tab1')">Tab 1</a>
    <a href="javascript:void(0)" onclick="openTab('tab2')">Tab 2</a>
</div>

<div id="tab1" class="tab">
    <div id="map">
       <div id="viewState" class="mapViewStateContainer"></div>
    </div>
</div>

<div id="tab2" class="tab">
    <h2>Tab 2 Content</h2>
    <p>This is the content of Tab 2.</p>
</div>

<script>
    function openTab(tabName) {
        var i, tabContent;
        tabContent = document.getElementsByClassName("tab");
        for (i = 0; i < tabContent.length; i++) {
            tabContent[i].style.display = "none";
        }
        document.getElementById(tabName).style.display = "block";
    }

    // By default, open the first tab
    openTab('tab1');
</script>

  <script type="text/javascript">
  
  // token from: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
    
  const deckgl = new deck.DeckGL({
    mapboxApiAccessToken: '',
    container: 'map',
    initialViewState: {
      longitude: 145,
      latitude: -37,
      zoom: 4
    },
    controller: true
  });
   
  </script>
  
  </body>
</html>
```

### Environment

- Framework version: https://unpkg.com/deck.gl@latest/dist.min.js
- Browser: Crhome
- OS: MacOS

### Logs

```
Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at e.value (dist.min.js:4539:18159)
    at e.value (dist.min.js:2107:6751)
    at e.value (dist.min.js:2107:13073)
    at t.value (dist.min.js:45:5613)
    at t.value (dist.min.js:45:7148)
    at t.value (dist.min.js:45:4056)
    at i (dist.min.js:45:6099)
```

**Comment by dcooley** [comment]
fixed in 8.9.33 release
