### ISSUE TITLE
deck: update of ScreenGridLayer({id: 'airbnb+houses-within-bbox'}): Deduced texture width does not match supplied width Error: Deduced texture width does not match supplied width

### ISSUE THREAD

**Issue by adnanwahab** [visgl/deck.gl#8252]
### Description

deck: update of ScreenGridLayer({id: 'airbnb+houses-within-bbox'}): Deduced texture width does not match supplied width Error: Deduced texture width does not match supplied width
<img width="1691" alt="Screenshot 2023-11-02 at 2 02 39 PM" src="https://github.com/visgl/deck.gl/assets/93497294/3c900d6b-167b-4938-a2d6-7930a11dede8">

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

ScreenGrid Layer works with the following code

  layers.push( new ScreenGridLayer({
    id: 'airbnb+houses-within-bbox-screengrid',
    data: 'https://raw.githubusercontent.com/adnanwahab/cooperation.party/turkey2/data/all-airbnb.json',
    opacity: 1.,
    getPosition: d => [d[1], d[0]],
    getWeight: () => 1,
    cellSizePixels: 30 - 10 * currentViewState.zoom,  //change on zoomLevel
    //colorRange,
    getFillColor: d => {
      let rgb = d3.rgb(interpolateRainbow(d[0]))
      return [rgb.r, rgb.g, rgb.b]
    },
  }))

### Steps to Reproduce

app is live on cooperation.party
Layer renders fine but after zooming and panning out a few times it throws an exception

deck: update of ScreenGridLayer({id: 'airbnb+houses-within-bbox'}): Deduced texture width does not match supplied width Error: Deduced texture width does not match supplied width

is there a way to avoid this error by setting a dedicated texture width

### Environment

- Framework version:
- Browser:
- OS:

### Logs

deck.ts:262 deck: update of ScreenGridLayer({id: 'airbnb+houses-within-bbox-screengrid'}): Deduced texture width does not match supplied width Error: Deduced texture width does not match supplied width
    at assert4 (assert.js:5:11)
    at Texture2D._deduceImageSize (texture.js:690:5)
    at Texture2D._deduceParameters (texture.js:664:29)
    at Texture2D.initialize (texture.js:126:59)
    at Texture2D.resize (texture.js:219:19)
    at GPUGridAggregator._setupFramebuffers (gpu-grid-aggregator.js:493:20)
    at GPUGridAggregator._runAggregation (gpu-grid-aggregator.js:465:10)
    at GPUGridAggregator.run (gpu-grid-aggregator.js:208:17)
    at ScreenGridLayer._updateAggregation (grid-aggregation-layer.ts:175:25)
    at ScreenGridLayer.updateState (grid-aggregation-layer.ts:73:12)

**Comment by Pessimistress** [comment]
Please create a Code Sandbox that reproduces your issue.

**Comment by Pessimistress** [comment]
Closing for inactivity. Reopen if able to reproduce.
