### ISSUE TITLE
[Bug] The Cesium Google 3D Tiles endpoint provides an _incorrect_ url for the Tile3dLayer to use with the CesiumIonLoader

### ISSUE THREAD

**Issue by vsigno** [visgl/deck.gl#8437]
### Description

I’m trying to load Google 3DTiles as a `MapBoxLayer` using `Tile3DLayer` and `CesiumIonLoader`. 

using:

```js
const CesiumLayer= new MapboxLayer({
    id: 'tiles',
    type: Tile3DLayer,
    data: 'https://assets.ion.cesium.com/2275207/tileset.json', //Google 3DTiles asset
    loader: CesiumIonLoader,
    loadOptions: {
  'cesium-ion': {accessToken: 'AccessToken'}
},
```
output this error:

```bash
Uncaught (in promise) Error: loader assertion failed.
    at assert (assert.ts:7:11)
    at getIonTilesetMetadata (ion.ts:23:3)
    at async Tile3DLayer._loadTileset (tile-3d-layer.ts:188:30)
```

Looking at the Cesium endpoint API, I can see that the result is of type `3DTiles`, however is not formatted as the usual Cesium asset, but the URL is nested in a _options_ object

```json
{
    "type": "3DTILES",
    "externalType": "3DTILES",
    "options": {
        "url": "https://tile.googleapis.com/v1/3dtiles/root.json?key=<KEY>"
    },
    "attributions": [
        {
            "html": "<span><a href=\"https://cesium.com\" target=\"_blank\"><img alt=\"Cesium ion\" src=\"https://assets.ion.cesium.com/ion-credit.png\"></a></span>",
            "collapsible": false
        },
        {
            "html": "<a href=\"https://cesium.com/pricing/\" target=\"_blank\">Upgrade for commercial use.</a>",
            "collapsible": false
        },
        {
            "html": "<span><img alt=\"Google\" src=\"https://assets.ion.cesium.com/google-credit.png\"></span>",
            "collapsible": false
        }
    ]
}

```

the usual Cesium asset response is this:

```json
{
    "type": "3DTILES",
    "url": "https://assets.ion.cesium.com/us-east-1/asset_depot/96188/OpenStreetMap/2023-01-02/tileset.json?v=16",
    "accessToken": "<ACCESS Token>",
    "attributions": [
        {
            "html": "<span><a href=\"https://cesium.com\" target=\"_blank\"><img alt=\"Cesium ion\" src=\"https://assets.ion.cesium.com/ion-credit.png\"></a></span>",
            "collapsible": false
        },
        {
            "html": "<a href=\"https://cesium.com/pricing/\" target=\"_blank\">Upgrade for commercial use.</a>",
            "collapsible": false
        },
        {
            "html": "<span>© <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">OpenStreetMap</a> contributors</span>",
            "collapsible": true
        }
    ]
}
```

Changing the `data` to that URL, and removing the `Loader` and `load options` makes everything work as expected.

```js
const CesiumLayer= new MapboxLayer({
    id: 'tiles',
    type: Tile3DLayer,
    data: 'https://tile.googleapis.com/v1/3dtiles/root.json?key=<KEY>'
)}
```

I suspect the issue lies with Deck.gl’s `Tile3DLayer`, and not with the Loader.gl’s `CesiumIonLoader` (well, the issue is actually the response from Cesium).
A solution would be for the `Tile3DLayer` to check if `url` exists in the response, if not look at `options.url` and ignore `CesiumIonLoader`.

Libraries used:
- _Deckgl 8.9.0_
- _Loaders.gl/3d-tiles 3.4.14_ (4.0.4 gave me a contex._parse error)
- _MapboxGL 3.1.0_

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

`Tile3DLayer` should handle the Cesium response and visualise the Google 3D tiles. 

### Steps to Reproduce

```js
import {MapboxLayer} from '@deck.gl/mapbox';
import { CesiumIonLoader } from '@loaders.gl/3d-tiles';
import mapboxgl from 'mapbox-gl';
import {Tile3DLayer} from '@deck.gl/geo-layers';
import {Deck, log} from '@deck.gl/core';

const INITIAL_VIEW_STATE = {
    longitude: -0.12599998138976254, //0.12,
    latitude: 51.521592969384706, //51.5, 
    zoom: 15,
    bearing: 0,
    pitch: 0
};

// Set your API key here
const API_TOKEN_Mapbox = 'TOKEN';
mapboxgl.accessToken = API_TOKEN_Mapbox;

// MapBox Vector Tile
const map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/dark-v10',
    interactive: true,
    center: [INITIAL_VIEW_STATE.longitude, INITIAL_VIEW_STATE.latitude],
    zoom: INITIAL_VIEW_STATE.zoom,
    bearing: INITIAL_VIEW_STATE.bearing,
    pitch: INITIAL_VIEW_STATE.pitch
});

map.on('load', () => {

 const CesiumLayer= new MapboxLayer({
     id: 'tiles',
     type: Tile3DLayer,
     data: 'https://assets.ion.cesium.com/2275207/tileset.json',
     loader: CesiumIonLoader,
     loadOptions: {
     'cesium-ion': {accessToken: '<TOKEN>'}
 },
},
});
map.addLayer(CesiumLayer);
});
```

```html



### Environment

- Framework version:
- Browser:
- OS:


### Logs

_No response_

**Comment by vsigno** [comment]
Thanks, I agree with you that this is an API issue rather than a loaderGL issue. I have just posed a question on the Cesium community regarding the endpoint response. I’m using Cesium instead of Google to avoid registering for an additional service, as the visualization I’m creating utilizes other assets from Cesium. Of course, you are right, the easiest workaround would be to use Google directly.

I’ll have a look at the `dataTransform` to see if I can access the URL. However, I’m not sure it will work, as I need the Cesium loader to perform the authentication (and get the Google URL with the appended Token), but the same loader needs to be disabled in order to correctly load the Google tiles.

**Comment by vsigno** [comment]
Update from the Cesium Team, the [response](https://community.cesium.com/t/cesium-api-endpoint-for-google-3d-tiles-asset-provides-an-incorrect-url/29510) from the endpoint is as expected. Cesium uses both internal and external assets, and the two different responses reflect that difference. So the issue still really lies with the `CesiumIonLoader` that, at the moment, cannot handle the external assets. I'll have a look to the [ion.ts](https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/src/lib/ion/ion.ts).

**Comment by felixpalmer** [comment]
@vsigno could you try and open an PR in the loaders.gl repo? There is a function for [parsing the metadata](https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/src/lib/ion/ion.ts#L13) which I think could be modified here

**Comment by LukasPoque** [comment]
I'm facing the same issue with deckgl 9.1.0

I saw there was a commit in October 2024 in the loaders.gl repo that should fix this: https://github.com/visgl/loaders.gl/commit/7dc03746ad1d7a49c833acacdfa9ebdc1e9d8574

But I can't get Google3DTiles rendered in deck.gl when I fetch them via the cesium rest API. When I grab the access token for Google from the initial response of Cesium and put this in a Tile3DLayer to access the data through Google Maps API directly, I can see the tiles. So there is still something wrong with the cesium loader when it tries to parse the response for an "external" tileset like google photorealistic tiles via the cesium API.

**Comment by vsigno** [comment]
Hey @LukasPoque, I didn't have time to follow up with the PR, but in the meantime, I found a workaround that works fine for what I need to do: using Cesium ION to load the GTiles without the Google token. Tested with `DeckGL 9.1.1` and `LoadersGL 4.2.0`

Create the request using the Google 3D tiles endpoint on Cesium:

```js
let CESIUM_EndPoint="https://api.cesium.com/v1/assets/2275207/endpoint"//Google 3D Tiles endpoint on cesium
let CESIUM_AccessToken="CESIUM Access Token from the ION Dashboard"

let Cesium_GTiles

async function fetchRemoteJSON(inputData) {
  const response = await fetch(inputData);
  const dataJson = await response.json();
  return dataJson;
}

await fetchRemoteJSON(CESIUM_EndPoint+"?access_token="+CESIUM_AccessToken)
.then(dataJson => {Cesium_GTiles=dataJson; console.log(Cesium_GTiles.options.url);
});
```

And then you can load the `Cesium_GTiles.options.url` with the `Tile3DLayer` _data_

```js
const tilesGM= new Tile3DLayer({
  id: 'tiles',
  data: Cesium_GTiles.options.url,//this is the url returned by the fetch request
})

const deckOverlay = new MapboxOverlay({ 
  interleaved: true, 
    layers: [
    //[..other layers..]
    tilesGM
  ]
})
```
