### ISSUE TITLE
[Bug] ScenegraphLayer: load quantized glb

### ISSUE THREAD

**Issue by skemaikin** [visgl/deck.gl#9213]
### Description

I have a quantized  model in glb-file.  `ScenegraphLayer` from `deck.gl v 9.0.33` cannot load quantized glb-file. But  `deck.gl v 8.8.2` do it without any problems. Simple app that demonstrates the problem: [glb-loader](https://drive.google.com/file/d/12vCBBV8GMGfmLq0e02P8yJe_tGXUmXhC/view?usp=sharing)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

loading quantized glb

### Steps to Reproduce

1. unpack archive
2. `npm install`
3. `npm start`
4. `localhost:3001`

### Environment

- Framework version: deckgl@9.0.33
- Browser: Chrome, FireFox
- OS: Ubuntu 22.04
- React: v18.18.2

### Logs

```
deck: update of ScenegraphLayer({id: 'test'}): size: 3 Error: size: 3
    at getVertexFormatFromAttribute (vertex-format-from-attribute.js:69:1)
    at getAttributeBuffersFromGeometry (gpu-geometry.js:86:1)
    at makeGPUGeometry (gpu-geometry.js:48:1)
    at Model.setGeometry (model.js:293:1)
    at new Model (model.js:153:1)
    at createGLTFModel (create-gltf-model.js:96:1)
    at GLTFInstantiator.createPrimitive (gltf-instantiator.js:95:1)
    at gltf-instantiator.js:80:1
    at Array.map (<anonymous>)
    at GLTFInstantiator.createMesh (gltf-instantiator.js:80:1)

```

**Comment by skemaikin** [comment]
the problem is still actual (
[quantized glb](https://drive.google.com/file/d/1P5GywoBWFjK9K30YfrTsFYliLKFM2E04/view?usp=sharing)
[non-quantized glb](https://drive.google.com/file/d/1olhAVM6Qp4y3D67F_F47L_0Q8YcMGH8t/view?usp=sharing)

**Comment by skemaikin** [comment]
still no answer (

**Comment by Jacqueline-Kelly** [comment]
Any update on this? I have the same error

**Comment by fmg-chris-taylor** [comment]
Any updates - running into this issue when trying to load a compressed glb file using quantization. Any known work arounds?
