### ISSUE TITLE
[Bug] HeatmapLayer example hangs

### ISSUE THREAD

**Issue by zxweed** [visgl/deck.gl#9274]
### Description

Example code at https://deckgl.readthedocs.io/en/latest/gallery/heatmap_layer.html hangs when zooming or panning.

The same is observed when running the example code in JupyterLab

### Flavors

- [ ] Script tag
- [ ] React
- [X] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Just open the [example page](https://deckgl.readthedocs.io/en/latest/gallery/heatmap_layer.html) and zoom/pan

### Environment

- Framework version: 0.9.1
- Browser: Chrome and Safari
- OS: MacOS

**Comment by duber-oai** [comment]
Issue needs a `pydeck` label.

From the console, it looks like a problem with the tooltip that is causing the application to freeze.

```
Uncaught TypeError: Cannot read properties of null (reading 'map')
    at Nz (widget-tooltip.js:126:53)
    at widget-tooltip.js:177:33
    at $x.onHover (tooltip.js:45:29)
    at ME.onHover (widget-manager.js:195:24)
    at sg._pickAndCallback (deck.js:583:36)
    at sg._onRenderFrame (deck.js:717:14)
    at Nx._renderFrame (animation-loop.js:256:20)
    at Nx.redraw (animation-loop.js:154:14)
    at Nx._animationFrame (animation-loop.js:244:14)
```
